### ISSUE TITLE
Bot does not  join anarchy server when server restarts

### ISSUE THREAD

**Issue by kickTROLL** [RattlesHyper/TrafficerMC#15]
The Here is the script I'm using 

![ss](https://user-images.githubusercontent.com/70624816/193715352-d31e9cd0-1662-4003-9c16-42d27d93d45c.PNG)

When i click on reconnect it does disconnects but the bot stays in the lobby.

**Comment by RattlesHyper** [comment]
Seems like a problem with your script, you can dm me or join the discord for script issues
