### ISSUE TITLE
Baritone support

### ISSUE THREAD

**Issue by carlos837** [RattlesHyper/TrafficerMC#16]
It would be cool

**Comment by adalmo** [comment]
yeah lol

**Comment by xiaozhu2007** [comment]
Yeah

**Comment by wendellmeset** [comment]
While it may seem simple (And dont quote me on this im not sure whether or not this runs a simulated client or another method). This application does not directedly load a game of minecraft (as far as I am aware again dont quote me) it hosts an account from your pc and controls them, and as such I do not beleive has the ability for mods to be implemented (however again I could be wrong) Plus a GUI would have to be made for all the baritone functions. However I definitely want to see this implemented as well!!!!

**Comment by RattlesHyper** [comment]
@wendellmeset you are right, this is not a normal client. it runs on a JS lib called mineflayer. There are some pathfinding and mining plugins but not as powerful as baritone.
