### ISSUE TITLE
No Linux Support Latest Version?

### ISSUE THREAD

**Issue by wendellmeset** [RattlesHyper/TrafficerMC#20]
It appears you forgot to add in the Linux artifacts. Or there is no Linux support, more info on this please?

**Comment by wendellmeset** [comment]
I do :(
Always better be safe than sorry lolz.

**Comment by evghenii12** [comment]
@wendellmeset I use it too u can run it through github rdp but maybe try to use wine or compile through node

**Comment by RattlesHyper** [comment]
alright ill add linux build, you can build it yourself too with the build guide by the way.

**Comment by RattlesHyper** [comment]
Linux build has been added to the releases.
