### ISSUE TITLE
it would be cool if you could see the graphical interface (to enter the captcha)

### ISSUE THREAD

**Issue by EleCtRoMiX578** [RattlesHyper/TrafficerMC#26]

**Comment by EleCtRoMiX578** [comment]
perhaps it can be made simple by transferring information about the image of the map in the hand

**Comment by f4r2** [comment]
well than u can try to do it by yourself using prismarine-viewer and mineflayer library

**Comment by RattlesHyper** [comment]
i have some plans but its not easy to implement
