### ISSUE TITLE
Cannot read properties of undefined

### ISSUE THREAD

**Issue by Waschkii** [RattlesHyper/TrafficerMC#29]
so im trying to bot my aternos server that is on 1.19.2 to test performance and im still getting: TypeError: Serialization error for play.toServer : SizeOf error for undefined : Cannot read properties of undefined (reading 'length')

**Comment by RattlesHyper** [comment]
does the server support lower version than 1.19.2? also you need to check if the proxied are working or not. you can join the discord so i can check the issue.
