### ISSUE TITLE
A Series Of Suggestions

### ISSUE THREAD

**Issue by wendellmeset** [RattlesHyper/TrafficerMC#39]
-1.19.4 Support
-Plugin Support (As in mineflayer scripts so that you can run any mineflayer script you want)
-Other basic functions (bodyguarding a player, add 'friends' to killaura (people to ignore), following a player, mining a specific block, area mining out an area, following a certain entity (ANYPLAYER, ANYMOB, or ANYVEHICLE)

Thats about it, since this runs on mineflayer , it should be pretty easy for the "other basic functions", and there is obviously tons of code for everything I listed already out there. As for the other 2 should be relatively simple!

**Comment by wendellmeset** [comment]
Why did you ignore my issue 😆 @RattlesHyper

**Comment by RattlesHyper** [comment]
1.19.4 support will be added as soon as possible. Other features are noted.

**Comment by wendellmeset** [comment]
Thank you, forgot to mention this feature as well: travelling to certain coordinates
