### ISSUE TITLE
1.20.X support

### ISSUE THREAD

**Issue by xch6nce** [RattlesHyper/TrafficerMC#49]
1.20 support?

**Comment by quangei** [comment]
https://github.com/quangei/TrafficerMC/releases/tag/v1.9.2

**Comment by quangei** [comment]
> 1.20 support?

https://github.com/quangei/TrafficerMC/releases/tag/v1.9.2

**Comment by MassivebutterpapperCodes** [comment]
is dis virus?

**Comment by Crexonus** [comment]
> is dis virus?

idk

**Comment by RattlesHyper** [comment]
Added 1.20 support.

**Comment by quangei** [comment]
> is dis virus?

No
