### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by kittenvr** [RattlesHyper/TrafficerMC#54]
there is a bug you cant stop it when starting it

**Comment by wendellmeset** [comment]
Yes you can, please provide more info or close the issue. Or EXACT STEPS to reproduce the problem.

**Comment by kittenvr** [comment]
> Yes you can, please provide more info or close the issue. Or EXACT STEPS to reproduce the problem.

Click start and spam stop

**Comment by kittenvr** [comment]
> > Yes you can, please provide more info or close the issue. Or EXACT STEPS to reproduce the problem.
> 
> Click start and spam stop

with like 100 bots

**Comment by RattlesHyper** [comment]
[STOP] stops sending more bots, if the bots are delayed because of internet they will still try to connect.
