### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by kittenvr** [RattlesHyper/TrafficerMC#57]
i dont think proxies work

**Comment by wendellmeset** [comment]
You are going to need a more description bit of info then that to receive any help, as its a problem on your end (my proxies and my friend's work perfectly)

Also, you have to use good proxies, you cant just use random or outdated ones!

**Comment by kittenvr** [comment]
> You are going to need a more description bit of info then that to receive any help, as its a problem on your end (my proxies and my friend's work perfectly)
> 
> Also, you have to use good proxies, you cant just use random or outdated ones!

Where do I get good proxies bc i use proxiescrape

**Comment by kittenvr** [comment]
> > You are going to need a more description bit of info then that to receive any help, as its a problem on your end (my proxies and my friend's work perfectly)
> > 
> > Also, you have to use good proxies, you cant just use random or outdated ones!
> 
> Where do I get good proxies bc i use proxiescrape

Or do I need to change settings bc i use default

**Comment by kittenvr** [comment]
Also @wendellmeset can you pr the follow thing

**Comment by RattlesHyper** [comment]
proxies are perfectly working, you just need good proxies and make sure you set the protocol.

**Comment by kittenvr** [comment]
> proxies are perfectly working, you just need good proxies and make sure you set the protocol.

on which site and which setings?
