### ISSUE TITLE
Proxy Oddities

### ISSUE THREAD

**Issue by User-For-Reviews** [RattlesHyper/TrafficerMC#63]
Bots do not connect when using the proxy function.
I don't think it can be an outdated proxy server because I use these https://github.com/TheSpeedX/PROXY-List and they are regularly updated, and moreover in a different program https://github.com/crpmax/mc-bots with their help, bots successfully log in. Even the health check (check file button) didn't help me. Check the program for errors. But if this is not the case, then please advise me what I can do to solve this problem, and what it may be related to. Here are all the errors I noticed:

Error: Socket closed
[undefined] socketClosed
[ProxyError] [Test] [112.124.2.212:1081] Error: Socket closed
[ProxyError] [Test] [51.75.126.150:60145] Error: write ECONNRESET
[ProxyError] [Test] [185.162.228.11:80] Error: Socks4 Proxy rejected connection - (undefined)
[ProxyError] [Test] [201.95.254.137:3128] Error: Proxy connection timed out
[ProxyError] [Test] [8.219.74.58:1234] Error: connect ETIMEDOUT 8.219.74.58:1234
[ProxyError] [Test] [153.101.67.170:9002] Error: Received invalid Socks5 initial handshake (invalid socks version)
handshake (invalid socks version)
[ProxyError] [Test] [05.135.170.126:8080] Error: getaddrinfo ENOTFOUND 05.135.170.126
[ProxyError] [Test] [67.43.236.20:9933] Error: connect ECONNREFUSED 67.43.236.20:9933

**Comment by Petrkiller2** [comment]
I have the smae problem with the new scraping feature (v2.3) and with my own proxies i found myself.

**Comment by RattlesHyper** [comment]
Proxy issues are being worked on, its something to do with the package used in the program to handle proxy connections.
