### ISSUE TITLE
not working for 1.20.2

### ISSUE THREAD

**Issue by dracocraft** [RattlesHyper/TrafficerMC#66]
its not working in 1.20.2

**Comment by CoderStealer** [comment]
1.20.2  is not supported in v2.3

**Comment by FrahHS** [comment]
1.20 will be supported?

**Comment by YiMengYanYu** [comment]
1.20.4?

**Comment by RattlesHyper** [comment]
Currently it supports up to 1.20.4, new versions will be added as soon as possible.
