### ISSUE TITLE
Request - Please Add Mods

### ISSUE THREAD

**Issue by ghostyARYAN** [RattlesHyper/TrafficerMC#7]
please Add mods like we can make auto grinder farm with the help of autoclicker , auto farming farm , like we can build customs mods as you previously added a script thing but it not support click holding and afk grinding.

**Comment by RattlesHyper** [comment]
Which features do you need exactly?

**Comment by ghostyARYAN** [comment]
Auto Clicker For Mob GRinding.

**Comment by RattlesHyper** [comment]
Ill try to add killaura

**Comment by RattlesHyper** [comment]
Added Kill-Aura.
