### ISSUE TITLE
Click

### ISSUE THREAD

**Issue by Healxwq** [RattlesHyper/TrafficerMC#74]
The game should be right clicked and left clicked (like hitting a block)

**Comment by kapibar21377** [comment]
winClick 12 1
Delay 15000
winClick 40 1
Delay 15000
winClick 34 1
Delay 15000
winClick 40 1
Delay 60000
startScript

**Comment by RattlesHyper** [comment]
The bot does not work like a normal Minecraft client. it simulates packets.
